#!/usr/bin/env bash
# @brief Shell hook generation for PixiEden.
# @description
# Writes the validated runtime hook and emits a small source command for Bash or zsh.

if [ -n "${PIXIED_HOOK_LOADED:-}" ]; then
    # shellcheck disable=SC2317 # Sourced by both the source and deployed CLI.
    return 0 2>/dev/null || exit 0
fi
PIXIED_HOOK_LOADED=1

# @description Return the generated runtime hook path.
# @stdout The absolute runtime hook path.
# @exitcode 0 Always.
pixied_hook_runtime_path() {
    printf '%s/runtime-hook.bash' "$PIXIED_CONFIG_DIR"
}

# @description Build the generated runtime hook from validated installation paths.
# The generated code validates state in a child Bash process before exporting
# anything into the shell that sources it.
#
# @stdout The generated runtime hook content.
# @exitcode 0 When content generation succeeds.
pixied_hook_runtime_content() {
    local account_literal state_dir_literal cli_literal
    local content
    printf -v account_literal '%q' "$PIXIED_ACCOUNT_HOME"
    printf -v state_dir_literal '%q' "$PIXIED_STATE_DIR"
    printf -v cli_literal '%q' "$PIXIED_DATA_DIR/bin/pixied"

    content="$({
        cat <<'RUNTIME_HEAD'
# Generated by pixied install. Do not edit.
_pixied_runtime_hook() {
    if [ -n "${PIXIED_RUNTIME_HOOK_ACTIVE:-}" ]; then
        return 0
    fi
    local state_file state_output pixied_cli_path
    local key value account_home machine_id home_mode local_home session_manager
    local data_dir config_dir state_dir command_bin pixi_home pixi_binary_path
    local direnv_path zellij_path hook_shell
    local path_result path_entry direnv_hook
RUNTIME_HEAD
        printf '    state_root=%s\n' "$state_dir_literal"
        printf '    account_home=%s\n' "$account_literal"
        printf '    pixied_cli_path=%s\n' "$cli_literal"
        cat <<'RUNTIME_BODY'
    machine_id=${PIXIED_MACHINE_ID:-}
    if [ -z "$machine_id" ]; then
        if ! machine_id=$(HOME="$account_home" PIXIED_ACCOUNT_HOME="$account_home" \
            PIXIED_STATE_DIR="$state_root" bash "$pixied_cli_path" __machine-id 2>/dev/null); then
            printf '%s\n' '[pixied] WARN runtime machine identity is unavailable; run pixied install first.' >&2
            return 0
        fi
    fi
    case "$machine_id" in
    '' | .* | *[!A-Za-z0-9._-]*)
        printf '%s\n' '[pixied] WARN runtime machine identity is invalid; run pixied install first.' >&2
        return 0
        ;;
    esac
    state_file="$state_root/machines/$machine_id/state"
    if ! state_output=$(HOME="$account_home" PIXIED_ACCOUNT_HOME="$account_home" \
        PIXIED_MACHINE_ID="$machine_id" PIXIED_STATE_DIR="$state_root" \
        PIXIED_RUNTIME_STATE_FILE="$state_file" bash "$pixied_cli_path" __runtime-state 2>/dev/null); then
        printf '%s\n' '[pixied] WARN runtime state is unavailable; run pixied install first.' >&2
        return 0
    fi
    account_home=""
    machine_id=""
    home_mode=""
    local_home=""
    session_manager=""
    data_dir=""
    config_dir=""
    state_dir=""
    command_bin=""
    pixi_home=""
    pixi_binary_path=""
    direnv_path=""
    zellij_path=""
    while IFS='=' read -r key value; do
        # This is the activation subset; the child CLI validates the full
        # state through pixied_runtime_apply_state before this output exists.
        case "$key" in
        machine_id) machine_id=$value ;;
        account_home) account_home=$value ;;
        home_mode) home_mode=$value ;;
        local_home) local_home=$value ;;
        session_manager) session_manager=$value ;;
        data_dir) data_dir=$value ;;
        config_dir) config_dir=$value ;;
        state_dir) state_dir=$value ;;
        command_bin) command_bin=$value ;;
        pixi_home) pixi_home=$value ;;
        pixi_binary_path) pixi_binary_path=$value ;;
        direnv_path) direnv_path=$value ;;
        zellij_path) zellij_path=$value ;;
        esac
    done <<< "$state_output"
    if [ -z "$account_home" ] || [ -z "$machine_id" ] || [ -z "$home_mode" ] ||
        [ -z "$local_home" ] || [ -z "$session_manager" ] || [ -z "$data_dir" ] ||
        [ -z "$config_dir" ] || [ -z "$state_dir" ] || [ -z "$command_bin" ] ||
        [ -z "$pixi_home" ] || [ -z "$pixi_binary_path" ] || [ -z "$direnv_path" ]; then
        printf '%s\n' '[pixied] WARN runtime state is incomplete; run pixied install first.' >&2
        return 0
    fi
    if [ "$session_manager" = zellij ] && [ -z "$zellij_path" ]; then
        printf '%s\n' '[pixied] WARN runtime Zellij state is incomplete; run pixied install first.' >&2
        return 0
    fi

    if [ "$home_mode" = nfs ] && [ "${PWD:-}" = "$account_home" ]; then
        if ! cd -- "$local_home"; then
            printf '%s\n' '[pixied] WARN could not enter the runtime local home.' >&2
            return 0
        fi
    fi

    export PIXIED_RUNTIME_HOOK_ACTIVE=1
    export PIXIED_RUNTIME_STATE_FILE="$state_file"
    export PIXIED_STATE_FILE="$state_file"
    export PIXIED_MACHINE_ID="$machine_id"
    export PIXIED_ACCOUNT_HOME="$account_home"
    export PIXIED_HOME_MODE="$home_mode"
    export PIXIED_LOCAL_HOME="$local_home"
    export PIXIED_SESSION_MANAGER="$session_manager"
    export PIXIED_DATA_DIR="$data_dir"
    export PIXIED_CONFIG_DIR="$config_dir"
    export PIXIED_STATE_DIR="$state_dir"
    export PIXIED_COMMAND_BIN="$command_bin"
    export PIXIED_PIXI_HOME="$pixi_home"
    export PIXIED_PIXI_BINARY_PATH="$pixi_binary_path"
    export HOME="$local_home"
    export PIXI_HOME="$pixi_home"
    export PIXI_CACHE_DIR="$pixi_home/cache"
    export PIXI_NO_PATH_UPDATE=1

    if [ -n "${ZSH_VERSION:-}" ]; then
        hook_shell=zsh
    else
        hook_shell=bash
    fi

    # This PATH logic is intentionally duplicated from pixied_path_prepend_unique:
    # the generated hook must remain self-contained after it is deployed.
    _pixied_path_is_present() {
        local candidate existing
        candidate=$1
        while IFS= read -r existing; do
            [ "$existing" = "$candidate" ] && return 0
        done <<PATH_RESULT
$path_result
PATH_RESULT
        return 1
    }
    path_result=""
    for path_entry in "$command_bin" "$data_dir/bin" "$pixi_home/bin"; do
        [ -n "$path_entry" ] || continue
        if ! _pixied_path_is_present "$path_entry"; then
            [ -z "$path_result" ] || path_result="${path_result}:"
            path_result="${path_result}${path_entry}"
        fi
    done
    while IFS= read -r path_entry; do
        [ -n "$path_entry" ] || continue
        if ! _pixied_path_is_present "$path_entry"; then
            [ -z "$path_result" ] || path_result="${path_result}:"
            path_result="${path_result}${path_entry}"
        fi
    done < <(printf '%s\n' "${PATH:-}" | tr ':' '\n')
    export PATH="$path_result"

    case $- in
    *i*)
        if direnv_hook=$("$direnv_path" hook "$hook_shell" 2>/dev/null); then
            if [ -n "$direnv_hook" ] && ! eval "$direnv_hook"; then
                printf '%s\n' '[pixied] WARN dedicated direnv hook failed.' >&2
            fi
        else
            printf '%s\n' '[pixied] WARN dedicated direnv hook is unavailable.' >&2
        fi
        ;;
    esac

    case $- in
    *i*)
        if [ -t 0 ] && [ -t 1 ] && [ -z "${CI:-}" ] &&
            [ "$session_manager" = zellij ] && [ -z "${ZELLIJ:-}" ]; then
            if ! "$pixied_cli_path" shell; then
                printf '%s\n' '[pixied] WARN automatic runtime start failed.' >&2
            fi
        fi
        ;;
    esac
    return 0
}
_pixied_runtime_hook
unset -f _pixied_runtime_hook 2>/dev/null || :
unset -f _pixied_path_is_present 2>/dev/null || :
RUNTIME_BODY
    })"
    printf '%s' "$content"
}

# @description Generate and hash the runtime hook while the install lock is held.
# The state hash is set in memory and is persisted by the install caller after
# the generated file has been committed.
#
# @set PIXIED_STATE[runtime_hook_path] string The generated hook path.
# @set PIXIED_STATE[runtime_hook_hash] string The generated hook hash.
# @exitcode 0 When the hook is written and hashed.
# @exitcode 1 When the hook cannot be written.
pixied_hook_generate_runtime() {
    local runtime_path content
    runtime_path=$(pixied_hook_runtime_path)
    pixied_state_set runtime_hook_path "$runtime_path"
    unset 'PIXIED_STATE[runtime_hook_hash]'
    content=$(pixied_hook_runtime_content)
    pixied_atomic_write "$runtime_path" "$content"
    pixied_state_set runtime_hook_hash "$(pixied_sha256_file "$runtime_path")"
}

# @description Emit shell code that sources the verified runtime hook.
# @stdout A shell source command only.
# @exitcode 0 Always.
pixied_hook_emit() {
    local runtime_path
    runtime_path=$(pixied_hook_runtime_path)
    printf '. %q\n' "$runtime_path"
}
